#!/usr/bin/env python3
# =============================================================================
# oracle/gen_ieee_oracle_bridge_tests.py
# -----------------------------------------------------------------------------
# IEEE binary64 ↔ ℝ bridge fixtures for the three chord product faces
# (claimId 0007-ieee-oracle-bridge).
#
# Adapters on existing ADR-0006 keywords — no new wire token, no FFI, no
# RocqRefRunner, no extract `eval` collapse:
#
#   INTERSECT_FILTERED   NodingNG Hit / Empty (IEEE coords on the wire)
#   INTERSECT_POINT_XY   NodingNG Hit midpoint (0.5, 0.5)
#   OVERLAY_UNIFIED      OverlayNG / RelateNG 67-c parallel chords
#   ORIENT               int-safe finite decode (CCW unit triangle)
#
# Ground truth: theories-flocq/IeeeRBridge.v locked points + NodingNG
# crossing / disjoint witnesses + RelateNodingLineLineExtPinned 67-c.
#
#   N1  NODINGNG-HIT     diagonals (0,0)-(1,1) × (0,1)-(1,0) → POINT
#   N2  NODINGNG-HIT-XY  same pair → XY 0x1p-1 0x1p-1
#   N3  NODINGNG-EMPTY   67-c parallels (0,0)-(1,0) × (0,1)-(1,1) → NONE
#   N4  OVERLAY-67C      same parallels → FFFFFFFFF
#   N5  OVERLAY-HIT      diagonals → 212FF1FF2 (contact)
#   N6  ORIENT-INTSAFE   (0,0) (1,0) (0,1) → POS
#   N7  HEX-WIRE         same Hit via 0x0p+0 / 0x1p+0 spellings → POINT
#
# Run from repo root:
#   python3 oracle/gen_ieee_oracle_bridge_tests.py
#   python3 oracle/gen_ieee_oracle_bridge_tests.py --write-fixture
# Exit nonzero iff a proven invariant is violated.
# =============================================================================
import argparse
import os
import subprocess
import sys

BIN = os.environ.get("ORACLE_BIN", "oracle/oracle_bin")
FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "ieee_oracle_bridge_tests.txt")

violations = 0
lines = []


def emit(s=""):
    lines.append(s)
    print(s)


def run_raw(stdin):
    out = subprocess.run([BIN], input=stdin, capture_output=True, text=True)
    if out.returncode != 0:
        return f"ERR rc={out.returncode} {out.stderr.strip()}"
    text = out.stdout.strip()
    return text.splitlines()[-1] if text else "ERR empty"


def expect(label, got, want):
    global violations
    if got != want:
        violations += 1
        emit(f"!! {label}: got {got!r} want {want!r}")
    else:
        emit(f"ok {label}: {got}")


HIT = """INTERSECT_FILTERED
0 0
1 1
0 1
1 0
"""

HIT_XY = """INTERSECT_POINT_XY
0 0
1 1
0 1
1 0
"""

HIT_HEX = """INTERSECT_FILTERED
0x0p+0 0x0p+0
0x1p+0 0x1p+0
0x0p+0 0x1p+0
0x1p+0 0x0p+0
"""

EMPTY_67C = """INTERSECT_FILTERED
0 0
1 0
0 1
1 1
"""

OVERLAY_67C = """OVERLAY_UNIFIED
1
C 0 0 1 0
1
C 0 1 1 1
"""

OVERLAY_HIT = """OVERLAY_UNIFIED
1
C 0 0 1 1
1
C 0 1 1 0
"""

ORIENT_CCW = """ORIENT
0 0
1 0
0 1
"""


def write_fixture():
    """Static protocol transcripts (IEEE on the wire). Regeneration target."""
    body = """# ieee_oracle_bridge_tests.txt
# claimId: 0007-ieee-oracle-bridge
# Regenerated by: python3 oracle/gen_ieee_oracle_bridge_tests.py --write-fixture
#
# Existing ADR-0006 keywords only. IEEE binary64 tokens (decimal or %h).
# NodingNG Hit/Empty + OverlayNG/RelateNG 67-c parallel chords.

# N1 NodingNG Hit — unit-square diagonals
INTERSECT_FILTERED
0 0
1 1
0 1
1 0
# expect: POINT

# N2 NodingNG Hit midpoint (int-safe 1/2)
INTERSECT_POINT_XY
0 0
1 1
0 1
1 0
# expect: XY 0x1p-1 0x1p-1

# N3 NodingNG Empty / RelateNG 67-c parallels
INTERSECT_FILTERED
0 0
1 0
0 1
1 1
# expect: NONE

# N4 OverlayNG / RelateNG 67-c — disjoint parallel unit chords
OVERLAY_UNIFIED
1
C 0 0 1 0
1
C 0 1 1 1
# expect: FFFFFFFFF

# N5 OverlayNG contact on the NodingNG crossing
OVERLAY_UNIFIED
1
C 0 0 1 1
1
C 0 1 1 0
# expect: 212FF1FF2

# N6 ORIENT int-safe finite decode
ORIENT
0 0
1 0
0 1
# expect: POS <hex-area>

# N7 same Hit via IEEE hex-float spellings
INTERSECT_FILTERED
0x0p+0 0x0p+0
0x1p+0 0x1p+0
0x0p+0 0x1p+0
0x1p+0 0x0p+0
# expect: POINT
"""
    with open(FIXTURE, "w", encoding="utf-8") as handle:
        handle.write(body)
    emit(f"wrote {FIXTURE}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-fixture", action="store_true",
                        help="rewrite oracle/ieee_oracle_bridge_tests.txt")
    args = parser.parse_args()

    if args.write_fixture:
        write_fixture()
        return 0

    if not os.path.isfile(BIN):
        emit(f"SKIP: {BIN} not built (oracle/oracle_bin is gitignored).")
        emit("Build via the pinned toolchain, then re-run.")
        return 0

    emit("# IEEE↔R bridge (IeeeRBridge.v) on existing ADR-0006 keywords")
    expect("N1 nodingng hit", run_raw(HIT), "POINT")
    xy = run_raw(HIT_XY)
    # INTERSECT_POINT_XY prints "XY <x_hex> <y_hex>"; 0.5 is 0x1p-1.
    if xy.startswith("XY ") and "0x1p-1" in xy:
        emit(f"ok N2 nodingng hit xy: {xy}")
    else:
        expect("N2 nodingng hit xy", xy, "XY 0x1p-1 0x1p-1")
    expect("N3 nodingng empty / 67-c", run_raw(EMPTY_67C), "NONE")
    expect("N4 overlay 67-c parallels", run_raw(OVERLAY_67C), "FFFFFFFFF")
    expect("N5 overlay nodingng hit", run_raw(OVERLAY_HIT), "212FF1FF2")
    orient = run_raw(ORIENT_CCW)
    if orient.startswith("POS"):
        emit(f"ok N6 orient int-safe: {orient}")
    else:
        expect("N6 orient int-safe", orient.split()[0] if orient else orient, "POS")
    expect("N7 hex-float hit", run_raw(HIT_HEX), "POINT")

    if violations:
        emit(f"::error::IEEE↔R bridge violated {violations} proven invariant(s).")
        return 1
    emit("IEEE↔R bridge invariants N1-N7 ok.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
